biblioteca_online/biblioteca_online/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin', admin.site.urls),
    path('', include('usuario.urls')),
    path('', include('bibliotecario.urls')),
    path('', include('core.urls')),
]

biblioteca_online/core/urls.py
from django.urls import path, include
from . import views
app_name = "core"

urlpatterns = [
   path('main/', views.main_frontend, name="frontendmain"),
   path('main/bookdetail/<str:isbn>/', views.bookdetail_frontend, name="bookdetailmain"),
   path('main/prestamo/', include('prestamos.urls')),
   # links que manejan solicitudes del carrito
   path('add_book/', views.add_book, name='add_book'),
   path('crear_solicitud/', views.crear_prestamo, name='crear_solicitud'),
   path('eliminar_libro/', views.eliminar_libro, name='eliminar_libro'),
   path('print_carrito/<int:timestamp>/', views.print_carrito, name='print_carritos'),
]

biblioteca_online/usuario/urls.py
from django.urls import path, include
from . import views

app_name = "usuario"

urlpatterns = [
   path('login/', views.login_user, name="user_login"),
   path('logingout/', views.logout_user, name="user_logout"),
   path('register', views.register, name="user_register"),
   path('', views.home_page, name="welcome_page"),
   path('confUsuario/', views.conf_user, name="configure_page"),
   path('soliUser/', views.solicitud_user, name="solicitud_user"),
   path('confirmar_email/', views.confirmar_email, name='confirmar_email'),
   path('informacion_registro/', views.informacion_registro, name='informacion_registro'),
   path('cambiar_password/', views.cambiar_password, name='cambiar_password'),
   path('eliminar-cuenta/', views.eliminar_cuenta, name='eliminar_cuenta'),
    path('confirmar-eliminar-cuenta/', views.confirmar_eliminar_cuenta, name='confirmar_eliminar_cuenta'),
]

biblioteca_online/usuario/models.py
from django.db import models
from django.contrib.auth.models import User
import requests
from core.models import Actividad
from django.dispatch import receiver
from django.db.models.signals import post_save

# Create your models here.
class Usuario(models.Model):
   user = models.OneToOneField(User, on_delete=models.CASCADE)
   dni = models.IntegerField(null=True, unique=True) # Forzar en frontend
   fecha_nacimiento = models.DateField(null=True)
   compuesto = models.CharField(max_length=20, null=True)
   email_verificado = models.BooleanField(default=False)  # Nuevo campo
   email_confirmation_token = models.CharField(max_length=255, blank=True, null=True)  # Nuevo campo
   fecha_actualizacion = models.DateTimeField(auto_now=True)

   def __str__(self):
      return self.user.username + "_" + str(self.dni) 

@receiver(post_save, sender=User)
def create_Usuario(sender, instance, created,**kwargs):
    if created:
        Usuario.objects.create(user=instance)

def verificar_correo(email):
    kickbox_api_key = "test_2413259a4f8d4f2fcecdc0aa9bdb6796d865559417f3fd0774a244346bbd0cbc" 
    url = f"https://open.kickbox.com/v1/disposable/{email}"

    headers = {
        "Accept": "application/json",
        "Authorization": f"Bearer {kickbox_api_key}",
    }

    response = requests.get(url, headers=headers)

    if response.status_code == 200:
        data = response.json()
        return not data["disposable"]
    else:
        return False

class InformeUsuario(models.Model):
   id_informe = models.CharField(max_length=100, primary_key=True, unique=True, null=False, blank=False)
   id_usuario = models.ForeignKey(User, on_delete=models.CASCADE)
   id_actividad = models.ForeignKey(Actividad, on_delete=models.CASCADE)
   fecha_creacion = models.DateField(auto_now_add=True, null=False, blank=False)
   
   def __str__(self):
      return self.id_informe + " - " + str(self.id_usuario)

biblioteca_online/usuario/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class LoginForm(forms.Form):
   # email = forms.EmailField(required=True)
   username = forms.CharField(required=True)
   password = forms.CharField(required=True, widget=forms.PasswordInput())

class RegisterForm(UserCreationForm):
   email = forms.EmailField(required=True)
   class Meta:
      model = User
      fields = ["username","email", "password1", "password2"]

biblioteca_online/usuario/views.py
import secrets
from django.conf import settings
from django.urls import reverse
from django.core.mail import send_mail
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseBadRequest
from django.contrib.auth import get_user_model
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.decorators import user_passes_test
from django.contrib.auth.forms import PasswordChangeForm
from prestamos.prestamosbc.prestamosBC import BC_GetPrestamoOfUsuario
from usuario.usuariobc.usuariobc import BC_GetusuariobyUser
from .forms import RegisterForm, LoginForm
from .services import verificar_DNI
from .models import Usuario, verificar_correo
from django.contrib import messages
from django.shortcuts import render, redirect
from django.contrib.auth import login, authenticate, logout
from django.core.exceptions import ObjectDoesNotExist
from django.views.decorators.csrf import ensure_csrf_cookie

# @ensure_csrf_cookie -> fuerza que se actualice el csrf token

User = get_user_model()
# Create your views here.


def home_page(request):
    return render(request, "usuario/home.html")

@ensure_csrf_cookie
def login_user(request):
    if request.user.is_authenticated:
        return redirect("core:frontendmain")
    # TO-DO: Investigar si sería necesario forzar un logout aquí
    if request.method == "POST":
        form = LoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data.get("username")
            password = form.cleaned_data.get("password")
            user = authenticate(username=username, password=password)
            if user:
                usuario = BC_GetusuariobyUser(user)
                if usuario.email_verificado:
                    login(request, user)
                    return redirect("core:frontendmain")
                else:
                    messages.success(request, "Porfavor verifica tu correo")
                    return render(
                        request, "usuario/registration/login.html", {"form": form}
                    )
            else:
                messages.success(request, "Usuario o contraseña incorrectos")
                return render(
                    request, "usuario/registration/login.html", {"form": form}
                )
        else:
            messages.success(request, f"{form.errors}")
    else:
        form = LoginForm()
        print(form.errors)
        return render(request, "usuario/registration/login.html", {"form": form})

@ensure_csrf_cookie
def register(request):
    global usuarios
    global id_usuario
    if request.method == "POST":
        form = RegisterForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.email = form.cleaned_data.get("email")

            if verificar_correo(user.email):
                user.save()
                user.refresh_from_db()

                # Envía el correo de confirmación
                # Genera y guarda el token en el usuario
                token = generar_token()

                # Actualiza el modelo Usuario con el token generado
                usuario = Usuario.objects.get(user=user)
                usuario.email_confirmation_token = token
                usuario.save()

                enviar_correo_confirmacion(user.email, token)

                # Redirige a la página de confirmación de correo electrónico
                return redirect("usuario:informacion_registro")

            else:
                messages.error(request, "Correo electrónico no válido.")
        else:
            messages.error(request, f"{form.errors}")
    else:
        form = RegisterForm()
    return render(request, "usuario/registration/sign_up.html", {"form": form})

def generar_token():
    # Genera un token seguro usando secrets.token_urlsafe
    return secrets.token_urlsafe(32)

def enviar_correo_confirmacion(email, token):
    # Genera la URL de confirmación utilizando reverse
    # http://127.0.0.1:8000/
    confirm_url = "http://127.0.0.1:8000" + reverse("usuario:confirmar_email") + f"?token={token}"

    subject = "Confirmación de correo electrónico"
    # Incluye la URL de confirmación en el mensaje
    message = f"¡Gracias por registrarte! Por favor, haz clic en el siguiente enlace para verificar tu dirección de correo electrónico: {confirm_url}"
    from_email = settings.EMAIL_HOST_USER  # Utiliza la dirección de correo electrónico configurada en settings.py
    recipient_list = [email]

    send_mail(subject, message, from_email, recipient_list)

def informacion_registro(request):
    return render(request, 'usuario/informacion_registro.html')

def confirmar_email(request):
    # Verificar si el token de confirmación está presente en la solicitud
    token = request.GET.get('token')
    if not token:
        return HttpResponseBadRequest("Falta el token de confirmación en la URL.")
    
    try:
        # Realiza la consulta a través del modelo Usuario
        usuario = Usuario.objects.get(email_confirmation_token=token)
        # Marcar el correo electrónico como confirmado y guardar el usuario
        usuario.email_verificado = True
        usuario.save()

        messages.success(request, "¡Tu correo electrónico ha sido confirmado con éxito!")
        
        # Autenticar al usuario y redirigir según la lógica de tu aplicación
        user = authenticate(username=usuario.user.username, password=usuario.user.password)
        if user:
            login(request, user)
            if user.is_staff:
                # Redirigir al dashboard del bibliotecario
                if user.is_superuser:
                    return redirect("core:frontendmain")
                else:
                    return redirect("bibliotecario:dashboardBooker")
            else:
                return redirect("core:frontendmain")
        else:
            error_message = f"Error al autenticar al usuario. Credenciales: {usuario.user.username}/{usuario.user.password}"
            messages.error(request, error_message)
            return redirect("usuario:welcome_page")
    except Usuario.DoesNotExist:
        return HttpResponseBadRequest("Token de confirmación no válido.")


def logout_user(request):
    request.session.flush()  # Es necesario?
    logout(request)
    return redirect("usuario:welcome_page")


@ensure_csrf_cookie
def conf_user(request):
    if request.user.is_authenticated:
        if request.method == "POST":
            dni = request.POST.get("dni")
            print("dni: ", dni)
            if dni is None:
                return render(request, "usuario/confUser.html")
            result = verificar_DNI(dni)
            if result and 'nombres' in result:
                # agregar first_name, last_name y dni al usuario
                user = request.user
                user.first_name = result["nombres"]
                user.last_name = result["apellidoPaterno"] + " " + result["apellidoMaterno"]
                try:
                    user.usuario
                except ObjectDoesNotExist:
                    Usuario.objects.create(user=user)
                print(user.usuario.dni)
                user.usuario.dni = result["numeroDocumento"]
                user.usuario.save()
                user.save()
                messages.success(request, "Datos actualizados correctamente")
                # return redirect("core:frontendmain")
                return render(request, "usuario/confUser.html", {"result": result})
            else:
                messages.error(request, "DNI no válido")
                return render(request, "usuario/confUser.html")
        else:
            return render(request, "usuario/confUser.html")
    else:
        return redirect("usuario:user_login")

@ensure_csrf_cookie
def cambiar_password(request):
    if request.method == "POST":
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)
            messages.success(request, 'Contraseña cambiada exitosamente.')
            return redirect('usuario:configure_page')
        else:
            messages.error(request, 'Hubo un error al cambiar la contraseña. Por favor, corrige los errores en el formulario.')
            return render(request, 'usuario/cambiar_password.html', {'form': form})
    else:
        form = PasswordChangeForm(request.user)
        return render(request, 'usuario/cambiar_password.html', {'form': form})
    
@user_passes_test(lambda u: u.is_authenticated, login_url='usuario:user_login')
@login_required
def eliminar_cuenta(request):
    if request.method == 'POST':
        # Verificar la contraseña del usuario antes de eliminar la cuenta
        password = request.POST.get('password')
        if request.user.check_password(password):
            # Confirmación de eliminación
            return render(request, 'usuario/confirmar_eliminar_cuenta.html')
        else:
            messages.error(request, 'Contraseña incorrecta. Inténtalo de nuevo.')

    return render(request, 'usuario/eliminar_cuenta.html')

@user_passes_test(lambda u: u.is_authenticated, login_url='usuario:user_login')
@login_required
def confirmar_eliminar_cuenta(request):
    if request.method == 'POST':
        # Eliminar la cuenta del usuario
        request.user.delete()
        logout(request)
        messages.success(request, 'Tu cuenta ha sido eliminada con éxito.')
        return redirect('core:frontendmain')  # Puedes redirigir a donde desees después de la eliminación
    else:
        return redirect('usuario:eliminar_cuenta')

def solicitud_user(request):
    if request.user.is_authenticated:
        usuario:Usuario
        usuario = BC_GetusuariobyUser(request.user)
        prestamos = BC_GetPrestamoOfUsuario(usuario)
        context = {
            "prestamos": prestamos
        }
        return render(request, "usuario/solicitudUser.html",context)
    else:

biblioteca_online/templates/usuario/cambiar_password.html
{% extends "templates-base/user-base.html" %}

{% block style %}
    <!-- SimpleLightbox plugin CSS-->
    <link type="text/css" rel="stylesheet" href="\static\css\conf_eli_cuen.css" />
{% endblock style %}
{% block body %}
  <div class="container mt-5">
    <div class="row justify-content-center">
      <div class="col-md-4 text-center">
        <h2 class="mb-4">Cambiar Contraseña</h2>
        <img src="https://creazilla-store.fra1.digitaloceanspaces.com/emojis/45128/locked-with-key-emoji-clipart-xl.png" alt="Icono de contraseña" class="img-fluid mb-4 mx-auto">
      <button type="button" class="btn btn-primary" href="\templates\usuario\confUser.html">
        <a href="\confUsuario">Regresar</a></button>
      </div>
      <div class="col-md-6">
        <form method="post" action="{% url 'usuario:cambiar_password' %}" class="needs-validation" novalidate>
          {% csrf_token %}
          {{ form.as_p }}
          <center><button type="submit" class="btn btn-primary mt-3">Guardar Cambios</button></center>
        </form>
      </div>
    </div>
  </div>
{% endblock body %}

biblioteca_online/templates/usuario/confUser.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>Configuración</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        <link rel="stylesheet" href="\static\css\confStyle.css">
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

    </head>
    <body>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container-fluid">
                <a class="navbar-brand" href="#">Configuración</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'core:frontendmain' %}">Regresar a pagina principal</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>

        <br>
            <h1 class = ""><i class="fas fa-cogs"></i>Configuración de Usuario</h1>
            <h3 class = "">Bibliotinka</h3>
            <form method="POST">
                {% csrf_token %}
                <label for="username">Nombre de Usuario:</label>
                <input id="username" class="form-control" placeholder="Escribe tu nombre de usuario..." type="text" value="{{ user.username }}" data-sb-validations="required" required>
                <div class="invalid-feedback" data-sb-feedback="username:required">Este campo es requerido</div>
                
                <label for="email">Email:</label>
                <input id="email" class="form-control" placeholder="Escribe tu email..." type="email" value="{{ user.email }}" data-sb-validations="required,email" required>
                <div class="invalid-feedback" data-sb-feedback="email:required">Este campo es requerido</div>
                <div class="invalid-feedback" data-sb-feedback="email:email">El email no es valido</div>

                <label for="firstName">Nombre:</label>
                {% comment %} si user.first_name no está vacio, desplegarlo {% endcomment %}
                {% if user.first_name %}
                    <input id="firstName" name="first_name" class="form-control" placeholder="Escribe tu nombre..." type="text" value="{{ user.first_name }}" data-sb-validations="required" required disabled>
                {% else %}
                    <input id="firstName" name="first_name" class="form-control" placeholder="Escribe tu nombre..." type="text" value="{{ result.nombres }}" data-sb-validations="required" required disabled>
                {% endif %}
                <div class="invalid-feedback" data-sb-feedback="firstName:required">Este campo es requerido</div>

                <label for="lastName">Apellido:</label>
                {% if user.last_name %}
                    <input id="lastName" name="last_name" class="form-control" type="text" placeholder="Escribe tu apellido..." value="{{ user.last_name }}" data-sb-validations="required" required disabled>
                {% else %}
                    <input id="lastName" name="last_name" class="form-control" type="text" placeholder="Escribe tu apellido..." value="{{ result.apellidoPaterno }} {{ result.apellidoMaterno }}" data-sb-validations="required" required disabled>
                {% endif %}
                <div class="invalid-feedback" data-sb-feedback="lastName:required">Este campo es requerido</div>

                <label for="dni">DNI:</label>
                {% if user.dni %}
                    <input id="dni" name="dni" class="form-control" type="text" placeholder="Escribe tu DNI..." value="{{ user.dni }}" data-sb-validations="required" required>
                {% else %}
                    <input id="dni" name="dni" class="form-control" type="text" placeholder="Escribe tu DNI..." value="{{ result.numeroDocumento}}" data-sb-validations="required" required>
                {% endif %}
                <div class="invalid-feedback" data-sb-feedback="dni:required">Este campo es requerido</div>

                    <!--Botones-->
                    <button id = "boton1" class="btn btn-primary" type="submit">
                        Actualizar
                    </button>
                    <button id = "boton2" type="button" class="btn btn-primary" data-toggle="modal" >
                        <a href="{% url 'usuario:cambiar_password' %}">Cambiar contraseña</a>
                    </button>
                    <button id = "boton3" type="button" class="btn btn-secondary" data-toggle="modal" >
                        <a href="{% url 'usuario:eliminar_cuenta' %}">Eliminar cuenta</a>
                    </button>
            </form>
        <!-- Modal -->
        <div class="modal fade" id="exampleModal2" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Cambiar contraseña</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                </div>
                <div class="modal-body">
                    <label for="pass1">Contraseña: </label>
                    <input id="pass1" class="form-control" placeholder="Escribe tu clave" type="password"  data-sb-validations="required" required>
                    <div class="invalid-feedback" data-sb-feedback="pass1:required">Este campo es requerido</div>
            
                    <label for="pass2">Nueva Contraseña:</label>
                    <input id="pass2" class="form-control" placeholder="Escribe tu nueva clave" type="password"  data-sb-validations="required" required>
                    <div class="invalid-feedback" data-sb-feedback="pass2:required">Este campo es requerido</div>
            
                    <label for="pass3">Confirmar Contraseña:</label>
                    <input id="pass3" class="form-control" type="password" placeholder="Confirma tu clave"  data-sb-validations="required" required>
                    <div class="invalid-feedback" data-sb-feedback="pass3:required">Este campo es requerido</div>            
                </div>
                <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>
                <button type="button" class="btn btn-primary">Guardar</button>
                </div>
            </div>
            </div>
        </div>
        <!-- Modal -->
        <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Eliminar Cuenta</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                </div>
                <div class="modal-body">
                <label>{{user}} no queremos perderte. Estas seguro de Eliminar tu cuenta?</label>
                </div>
                <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>
                <button type="button" class="btn btn-primary">Eliminar Cuenta</button>
                </div>
            </div>
            </div>
        </div>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
    </body>
</html>

biblioteca_online/templates/usuario/confirmar_eliminar_cuenta.html
{% extends "templates-base/user-base.html" %}
{% block style %}
    <!-- Agrega la referencia a tu archivo de estilos CSS -->
    <link rel="stylesheet" href="\static\css\con_eli_cuen.css">
{% endblock style %}
{% block body %}
  <div class="container mt-5">
    <div class="row justify-content-center">
      <div class="col-md-4 text-center">
        <h2 class="mb-4">¿Estás seguro de que deseas eliminar tu cuenta?</h2>      </div>
      <div class="col-md-6">
        <form method="post" action="{% url 'usuario:confirmar_eliminar_cuenta' %}" class="needs-validation" novalidate>
          {% csrf_token %}
          <button type="submit" class="btn btn-danger mt-3">Sí, eliminar cuenta</button>
          <a href="{% url 'usuario:configure_page' %}" class="btn btn-secondary mt-3">No, volver atrás</a>
        </form>
      </div>
    </div>
  </div>
{% endblock body %}

biblioteca_online/templates/usuario/eliminar_cuenta.html
{% extends "templates-base/user-base.html" %}

{% block style %}
    <!-- Agrega la referencia a tu archivo de estilos CSS -->
    <link rel="stylesheet" href="\static\css\conf_eli_cuen.css">
{% endblock style %}

{% block body %}
  <div class="container mt-5">
    <div class="row justify-content-center">
      <div class="col-md-6 text-center">
        <h2 class="mb-4">Eliminar Cuenta</h2>
        <img src="https://cdn-icons-png.flaticon.com/512/216/216684.png" alt="Icono de eliminar cuenta" class="img-fluid mb-4 mx-auto">
      </div>
      <div class="col-md-6">
        <form method="post" action="{% url 'usuario:eliminar_cuenta' %}" class="needs-validation" novalidate>
          {% csrf_token %}
          <label for="password" class="form-label">Contraseña:</label>
          <input type="password" name="password" class="form-control" required>
          <button type="submit" class="btn btn-danger mt-3">Eliminar Cuenta</button>
        </form>
      </div>
    </div>
  </div>
{% endblock body %}

biblioteca_online/templates/usuario/home.html
{% extends "templates-base/user-base.html" %}
{% load static %}
{% block style %}
    <!-- SimpleLightbox plugin CSS-->
    <link type="text/css" rel="stylesheet" href="\static\css\welcome.css" />
{% endblock style %}
{% block body %}
    <!-- Navigation-->
    <nav class="navbar navbar-expand-lg navbar-light fixed-top py-3" id="mainNav">
      <div class="container px-4 px-lg-5">
          <a class="navbar-brand">BIBLIOTINKA</a>
          <button class="navbar-toggler navbar-toggler-right" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
          <div class="collapse navbar-collapse" id="navbarResponsive">
              <ul class="navbar-nav ms-auto my-2 my-lg-0">
                  <li class="nav-item"><a class="nav-link" href="login">Iniciar Sesión</a></li>
                  <li class="nav-item"><a class="nav-link" href="register">Registrarse</a></li>
              </ul>
          </div>
      </div>
  </nav>
  <!-- Masthead-->
  <header class="masthead">
      <div class="container px-4 px-lg-5 h-100">
          <div class="row gx-4 gx-lg-5 h-100 align-items-center justify-content-center text-center">
              <div class="col-lg-8 align-self-end">
                  <h1 class="text-white font-weight-bold">BIBLIOTINKA</h1>
                  <hr class="divider" />
              </div>
              <div class="col-lg-8 align-self-baseline">
                  <p class="text-white-75 mb-5">¡Revienta el pozo de la sabiduría y la lectura online!</p>
                  <a class="btn btn-primary btn-xl" href="main/">¡Empecemos!</a>
              </div>
          </div>
      </div>
  </header>
  <script src="{% static 'js\scripts.js' %}"></script>
{% endblock body %} 

biblioteca_online/templates/usuario/informacion_registro.html
<!-- En tu archivo templates/agregar_libro.html -->
{% extends "templates-base/user-base.html" %}

{% block body %}
<h2>¡Registro Exitoso!</h2>
<p>Se ha enviado un correo de confirmación a tu dirección. 
        Por favor, revisa tu bandeja de entrada y haz clic en el enlace de
         confirmación para completar el registro.</p>
{% endblock body %} 