biblioteca_online/biblioteca_online/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin', admin.site.urls),
    path('', include('usuario.urls')),
    path('', include('bibliotecario.urls')),
    path('', include('core.urls')),
]

biblioteca_online/core/urls.py
from django.urls import path, include
from . import views
app_name = "core"

urlpatterns = [
   path('main/', views.main_frontend, name="frontendmain"),
   path('main/bookdetail/<str:isbn>/', views.bookdetail_frontend, name="bookdetailmain"),
   path('main/prestamo/', include('prestamos.urls')),
   # links que manejan solicitudes del carrito
   path('add_book/', views.add_book, name='add_book'),
   path('crear_solicitud/', views.crear_prestamo, name='crear_solicitud'),
   path('eliminar_libro/', views.eliminar_libro, name='eliminar_libro'),
   path('print_carrito/<int:timestamp>/', views.print_carrito, name='print_carritos'),
]

biblioteca_online/usuario/urls.py
from django.urls import path, include
from . import views

app_name = "usuario"

urlpatterns = [
   path('login/', views.login_user, name="user_login"),
   path('logingout/', views.logout_user, name="user_logout"),
   path('register', views.register, name="user_register"),
   path('', views.home_page, name="welcome_page"),
   path('confUsuario/', views.conf_user, name="configure_page"),
   path('soliUser/', views.solicitud_user, name="solicitud_user"),
   path('confirmar_email/', views.confirmar_email, name='confirmar_email'),
   path('informacion_registro/', views.informacion_registro, name='informacion_registro'),
   path('cambiar_password/', views.cambiar_password, name='cambiar_password'),
   path('eliminar-cuenta/', views.eliminar_cuenta, name='eliminar_cuenta'),
    path('confirmar-eliminar-cuenta/', views.confirmar_eliminar_cuenta, name='confirmar_eliminar_cuenta'),
]

biblioteca_online/core/models.py
from django.db import models
from prestamos.models import Prestamo

# Create your models here.
class Categoria(models.Model):
   id_categoria = models.CharField(max_length=50, primary_key=True, unique=True, null=False, blank=False)
   nombre = models.CharField(max_length=50, null=False, blank=False)

   def __str__(self):
      return self.nombre

class Libro(models.Model):
   id_libro = models.CharField(max_length=100, primary_key=True, unique=True, null=False, blank=False)
   categoria = models.ForeignKey(Categoria, on_delete=models.CASCADE)
   title = models.CharField(max_length=100, null=False, blank=False)
   author = models.CharField(max_length=50, null=False, blank=False)
   isbn = models.CharField(max_length=50, null=False, blank=False)
   summary = models.CharField(max_length=4000, null=False, blank=False)
   image = models.URLField(max_length=240, null=True, blank=False)

   def save(self, *args, **kwargs):
        # Genera el ID del libro automáticamente
        if not self.id_libro:
            self.id_libro = f"{self.author[0].capitalize()}{self.isbn}"

        super().save(*args, **kwargs)

   def __str__(self):
      return self.title

class Estado(models.Model):
   id_estado = models.AutoField(primary_key=True, unique=True, null=False, blank=False)
   nombre = models.CharField(max_length=20, null=False, blank=False)

   def __str__(self):
      return str(self.id_estado) +" "+ self.nombre

class ReclamoUsuario(models.Model):
   id_reclamo = models.CharField(max_length=80, primary_key=True, unique=True, null=False, blank=False)
   id_prestamo = models.ForeignKey(Prestamo, on_delete=models.CASCADE)
   descripcion = models.CharField(max_length=1000, null=False, blank=False)
   imagen = models.ImageField(upload_to='reclamos/', null=True, blank=False)
   fecha_creacion = models.DateField(auto_now_add=True, null=False, blank=False)

   def __str__(self):
      return self.id_reclamo + "_FROM_" + self.id_usuario

class Actividad(models.Model):
   id_actividad = models.CharField(max_length=50, primary_key=True, unique=True, null=False, blank=False)
   descripcion = models.CharField(max_length=500, null=False, blank=False)

   def __str__(self):
      return self.id_actividad

biblioteca_online/core/forms.py
from django import forms
from .models import Libro

class LibroForm(forms.ModelForm):
    class Meta:
        model = Libro
        fields = '__all__'

biblioteca_online/core/views.py
from datetime import date, timedelta
from django.http import HttpResponseBadRequest, HttpResponseNotFound, JsonResponse
from django.core.paginator import Paginator
from django.shortcuts import render
from prestamos.prestamosbc.prestamosBC import BC_crearPrestamo
from usuario.usuariobc.usuariobc import BC_GetusuariobyUser
from core.utils.core_utils import CheckUserDNI
from core.corebc.librobc import DB_GetBookbyISBN
from core.models import Libro
from prestamos.models import Ejemplares


# Create your views here.
def main_frontend(request):
    query = request.GET.get("search")
    if query:
        libros = Libro.objects.filter(title__icontains=query).order_by("isbn")
    else:
        libros = Libro.objects.all().order_by("isbn")
    paginator = Paginator(libros, 8)
    page_number = request.GET.get("page")
    libros_pag = paginator.get_page(page_number)
    dni_check: bool
    dni_check = False
    if request.user.is_authenticated:
        dni_check = CheckUserDNI(request.user)

    ejemplares_count = {
        libro.isbn: Ejemplares.objects.filter(libro=libro, estado="1").count()
        for libro in libros
    }
    if "carrito" not in request.session:
        request.session["carrito"] = []
    context = {
        "libros": libros,
        "carrito": request.session["carrito"],
        "ejemplares_count": ejemplares_count,
        "dni_check": dni_check,
        "libros_pag": libros_pag,
    }

    return render(request, "core/store_mainpage/main_frontend.html", context)

def add_book(request):
    isbn_libro = request.GET.get("isbn_libro")
    print(f"Dato a agregar: {isbn_libro}")
    carrito = request.session.get("carrito", [])
    
    # Verificar si el libro ya está en el carrito
    if isbn_libro in carrito:
        return HttpResponseBadRequest("El libro ya está en la bandeja")

    carrito.append(isbn_libro)
    request.session["carrito"] = carrito

    # Obtener detalles del libro recién agregado
    libro = DB_GetBookbyISBN(isbn_libro)
    libro_info = {"isbn": libro.isbn, "titulo": libro.title}


    return JsonResponse({"num_items": len(carrito), "in_cart": True, "libro_info": libro_info})


def eliminar_libro(request):
    isbn_libro = request.POST.get("isbn_libro")
    print(f"Dato a eliminar: {isbn_libro}")
    carrito = request.session.get("carrito", [])
    carrito = [item for item in carrito if item["isbn"] != isbn_libro]
    request.session["carrito"] = carrito
    return JsonResponse({"success": True})


def print_carrito(request, timestamp):
    carrito = request.session.get("carrito", [])
    lista: list
    lista = []
    for item in carrito:
        libro: Libro
        libro = DB_GetBookbyISBN(item)
        lista.append({"isbn": libro.isbn, "titulo": libro.title})
    return JsonResponse({"carrito_detalle": lista})

def carrito_vacio(request):
    if "carrito" in request.session:
        del request.session["carrito"]
        request.session.save()
        return JsonResponse({"success": True})
    return JsonResponse({"success": False})  
    
def crear_prestamo(request):
    isbns = request.session.get("carrito", [])
    lista = []
    for isbn in isbns:
        local = DB_GetBookbyISBN(isbn)
        lista.append(local)
    id_ejemplares:str
    for item in lista:
        id_ejemplares = item + ','
    cadena_sin_ultimo_digito = id_prestamo[:-1]
    print(cadena_sin_ultimo_digito)
    id_ejemplares = cadena_sin_ultimo_digito
    prestado_estado = 'En espera'
    usuario = BC_GetusuariobyUser(request.user)
    id_usuario = usuario.id
    id_prestamo = request.user.id + date.today()
    fecha_iniprestamo = date.today()
    fecha_actual = date.today()
    fecha_finprestamo = fecha_actual + timedelta(days=20)
    fecha_devolucion = None
    if BC_crearPrestamo(id_prestamo,id_ejemplares,id_usuario,prestado_estado,fecha_iniprestamo,fecha_finprestamo,fecha_devolucion):
        if "carrito" in request.session:
            del request.session["carrito"]
            request.session.save()
        return main_frontend(request)
    return carrito_vacio(request)

def bookdetail_frontend(request, isbn):
    libro: Libro
    libro = DB_GetBookbyISBN(isbn)
    if libro is None:
        return HttpResponseNotFound("No se encontró el libro")

    dni_check: bool
    dni_check = False
    if request.user.is_authenticated:
        dni_check = CheckUserDNI(request.user)

    ejemplares_count = {
        libro.isbn: Ejemplares.objects.filter(libro=libro, estado="1").count()
    }
    if "carrito" not in request.session:
        request.session["carrito"] = []
    context = {
        "carrito": request.session["carrito"],
        "dni_check": dni_check,
        "libro": libro,
        "ejemplares_count": ejemplares_count,
    }
    return render(request, "core/store_mainpage/main_bookdetail.html", context)

biblioteca_online/templates/core/store_mainpage/main_bookdetail.html
{% extends 'templates-base/core-base.html' %}
{% load static %}
{% block titletext %}
  Bibliotinka - Detalle
{% endblock %}
{% block customcss %}
{% endblock %}
{% block customjs %}
  <script src="{% static 'js/bandeja_add.js' %}"></script>
{% endblock %}
{% load dictionary_tag %}
{% block bodycontent %}
  <!-- Product section -->
  <section class="py-5">
    <div class="container px-4 px-lg-5 my-5">
      <div class="row gx-4 gx-lg-5 align-items-center">
        <div class="col-md-6">
          <img class="card-img-top mb-5 mb-md-0" src="{{ libro.image }}" alt="https://user-images.githubusercontent.com/24848110/33519396-7e56363c-d79d-11e7-969b-09782f5ccbab.png" />
        </div>
        <div class="col-md-6">
          <div class="small mb-1">ISBN: {{ libro.isbn }}</div>
          <h1 class="display-5 fw-bolder">{{ libro.title }}</h1>
          <p class="lead">{{ libro.summary }}</p>
          {% if ejemplares_count|get_item:libro.isbn == 0 %}
            <a class="btn btn-outline-danger mt-auto disabled">Sin stock</a>
          {% elif libro.isbn in carrito %}
            <a class="btn btn-outline-primary mb-1 mt-auto disabled">Libro en bandeja</a>
          {% else %}
            <a class="btn btn-outline-dark mb-1 mt-auto add-to-cart" data-isbn-libro="{{ libro.isbn }}">Añadir al carro</a>
          {% endif %}
        </div>
      </div>
    </div>
  </section>
  <footer class="navbar fixed-bottom bg-dark">
    <div class="container-fluid">
      <a class="navbar-brand text-white"><p class="m-0 text-left">Copyright &copy; Bibliotinka 2023</p></a>
    </div>
  </footer>
{% endblock %}

biblioteca_online/templates/core/store_mainpage/main_frontend.html
{% extends 'templates-base/core-base.html' %}
{% load static %}
{% block titletext %}
  Bibliotinka - Homepage
{% endblock %}
{% block customcss %}
{% endblock %}
{% block customjs %}
  <script src="{% static 'js/bandeja_add.js' %}"></script>
  <script src="{% static 'js/plugins/automodal.js' %}"></script>
{% endblock %}
{% load dictionary_tag %}
{% block bodycontent %}
  {% comment %}INICIO MODALS{% endcomment %}
  {% if user.is_authenticated and not dni_check %}
    <div class="modal fade" id="dnimodal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <h1 class="modal-title fs-5" id="exampleModalLabel">Bienvenido a Bibliotinka</h1>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
          </div>
          <div class="modal-body">
            Nos da gusto que te hayas unido, <strong>{{ user }}</strong>,<br />
            nos hemos dado cuenta que no tienes tu DNI registrado,<br />
            para usar nuestros servicios necesitas un <strong>DNI registrado.</strong>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cerrar</button>
            <button href="{% url 'usuario:configure_page' %}" type="button" class="btn btn-primary"><a class = "text-light" href= {% url 'usuario:configure_page' %}>Ir a configuración</a></button>
          </div>
        </div>
      </div>
    </div>
  {% endif %}

  <div class="modal fade" id="notlogprestmodal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h1 class="modal-title fs-5" id="exampleModalLabel">¿Interesado en este libro?</h1>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          <p>Si desea pedir el préstamo del libro, por favor, inicie sesión.</p>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Seguiré revisando</button>
          <a href="{% url 'usuario:user_login' %}" class="btn btn-primary">Iniciar sesión</a>
        </div>
      </div>
    </div>
  </div>
  {% comment %}FIN DE MODALS{% endcomment %}

  <!-- Header -->
  <header class="bg-light py-5">
    {% if user.is_authenticated %}
      <div aria-live="polite" aria-atomic="true" class="position-relative">
        <div class="toast-container position-fixed top-0 end-0 p-3">
          <div id="liveToast" class="toast" role="alert" aria-live="assertive" aria-atomic="true">
            <div class="toast-header">
              <img src="https://www.iconsdb.com/icons/preview/royal-blue/info-xxl.png" class="rounded me-2" width="24" height="24" />
              <strong class="me-auto">Bibliotinka</strong>
              <button type="button" class="btn-close" data-bs-dismiss="toast" aria-label="Close"></button>
            </div>
            <div class="toast-body">
              Bienvenido de vuelta, <strong>{{ user }}</strong>
            </div>
          </div>
        </div>
      </div>
    {% endif %}
    <div class="container px-4 px-lg-5 my-5">
      <div class="text-center text-dark">
        <h1 class="display-4 fw-bolder">Bibliotinka</h1>
        <p class="lead fw-normal text-dark mb-0">Ofreciendo los mejores libros de nuestro repositorio</p>
      </div>
    </div>
  </header>
  <!-- Section -->
  <section class="py-5">
    <div class="container px-4 px-lg-5 mt-5">
      <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">
        {% comment %}inicio de carta{% endcomment %}
        {% if libros %}
          {% for libro in libros_pag %}
            <div class="col mb-5">
              <div class="card h-100">
                <!-- Product image -->
                <img class="card-img-top" src="{{ libro.image }}" alt="{{ libro.title }}" />
                <!-- Product details -->
                <div class="card-body p-4">
                  <div class="text-center">
                    <!-- Product name -->
                    <h5 class="fw-bolder">{{ libro.title }}</h5>
                    <!-- Product author -->
                    {{ libro.author }}
                  </div>
                </div>
                <!-- Product actions -->
                <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                  <div class="text-center">
                    <a class="btn btn-outline-dark mb-1 mt-auto" href="{% url 'core:bookdetailmain' libro.isbn %}">Detalle</a>
                    {% if ejemplares_count|get_item:libro.isbn == 0 %}
                      <a class="btn btn-outline-danger mt-auto disabled">Sin stock</a>
                    {% elif libro.isbn in carrito %}
                      <a class="btn btn-outline-primary mb-1 mt-auto disabled" href="#">Libro en bandeja</a>
                    {% else %}
                      {% if user.is_authenticated %}
                        <a class="btn btn-outline-dark mb-1 mt-auto add-to-cart" data-isbn-libro="{{ libro.isbn }}" data-bs-toggle="offcanvas">Añadir al carro</a>
                      {% else %}
                        <a class="btn btn-outline-dark mb-1 mt-auto" data-bs-toggle="modal" data-bs-target="#notlogprestmodal">Añadir al carro</a>
                      {% endif %}
                    {% endif %}
                  </div>
                </div>
              </div>
            </div>
          {% endfor %}
        {% else %}
          <div class="text-center">
            <div class="empty-img">
              <img src="https://component.gallery/static/8d36eaa25b6dcb026685101ebc379022/Empty%20state%20icon..svg" height="128" alt="..." />
            </div>
            <div class="text-center text-dark">
              <h1 class="h1 fw-bolder">¡Oops! Aquí no hay nada.</h1>
              <p class="lead fw-normal text-dark mb-0">Eliga los libros que desea.</p>
            </div>
          </div>
        {% endif %}
        {% comment %}fin de carta{% endcomment %}
      </div>
      <div class="pagination justify-content-center">
        <span class="step-links">
          {% if libros_pag.has_previous %}
            <a class="btn btn-primary" href="?page=1">« first</a>
            <a class="btn btn-primary" href="?page={{ libros_pag.previous_page_number }}">previous</a>
          {% endif %}

          <span class="current">Page {{ libros_pag.number }} of {{ libros_pag.paginator.num_pages }}.</span>

          {% if libros_pag.has_next %}
            <a class="btn btn-primary" href="?page={{ libros_pag.next_page_number }}">next</a>
            <a class="btn btn-primary" href="?page={{ libros_pag.paginator.num_pages }}">last »</a>
          {% endif %}
        </span>
      </div>
    </div>
  </section>
  <!-- Footer -->
  <footer class="navbar fixed-bottom bg-dark">
    <div class="container-fluid">
      <a class="navbar-brand text-white"><p class="m-0 text-left">Copyright &copy; Bibliotinka 2023</p></a>
    </div>
  </footer>
{% endblock %}