biblioteca_online/biblioteca_online/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin', admin.site.urls),
    path('', include('usuario.urls')),
    path('', include('bibliotecario.urls')),
    path('', include('core.urls')),
]

biblioteca_online/bibliotecario/urls.py
# bibliotecario/urls.py

from django.urls import path
from . import views

app_name = "bibliotecario"

urlpatterns = [
    path('panel_bibliotecario', views.panel_bibliotecario, name='panel_bibliotecario'),
    path('libros', views.libros, name='libros'),
    path('prestamos', views.prestamos, name='prestamos'),
    path('dashboardBooker/', views.dashboard_booker, name='dashboardBooker'),
    path('agregar_libro/', views.agregar_libro, name='agregar_libro'),
    path('registrar_ejemplar/', views.registrar_ejemplar, name='registrar_ejemplar'),
    path('registrar_prestamo/', views.registrar_prestamo, name='registrar_prestamo'),
    path('visualizar_prestamos/', views.visualizar_prestamos, name='visualizar_prestamos'),
    path('visualizar_prestamos/modificar/<str:id_prestamo>/', views.modificar_estado_prestamo, name='modificar_estado_prestamo'),
]

biblioteca_online/core/urls.py
from django.urls import path, include
from . import views
app_name = "core"

urlpatterns = [
   path('main/', views.main_frontend, name="frontendmain"),
   path('main/bookdetail/<str:isbn>/', views.bookdetail_frontend, name="bookdetailmain"),
   path('main/prestamo/', include('prestamos.urls')),
   # links que manejan solicitudes del carrito
   path('add_book/', views.add_book, name='add_book'),
   path('crear_solicitud/', views.crear_prestamo, name='crear_solicitud'),
   path('eliminar_libro/', views.eliminar_libro, name='eliminar_libro'),
   path('print_carrito/<int:timestamp>/', views.print_carrito, name='print_carritos'),
]

biblioteca_online/usuario/urls.py
from django.urls import path, include
from . import views

app_name = "usuario"

urlpatterns = [
   path('login/', views.login_user, name="user_login"),
   path('logingout/', views.logout_user, name="user_logout"),
   path('register', views.register, name="user_register"),
   path('', views.home_page, name="welcome_page"),
   path('confUsuario/', views.conf_user, name="configure_page"),
   path('soliUser/', views.solicitud_user, name="solicitud_user"),
   path('confirmar_email/', views.confirmar_email, name='confirmar_email'),
   path('informacion_registro/', views.informacion_registro, name='informacion_registro'),
   path('cambiar_password/', views.cambiar_password, name='cambiar_password'),
   path('eliminar-cuenta/', views.eliminar_cuenta, name='eliminar_cuenta'),
    path('confirmar-eliminar-cuenta/', views.confirmar_eliminar_cuenta, name='confirmar_eliminar_cuenta'),
]

biblioteca_online/templates/templates-base/core-base.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no" />
    <title>
      {% block titletext %}

      {% endblock %} 
    </title>

    <script src="{% static 'js/bandeja_add.js' %}"></script>
    <!-- Enlaces a los archivos CSS de Bootstrap -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous" />
    <!-- Otros estilos CSS personalizados, si los tienes -->
    <!-- Fonts and icons -->
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700,200" rel="stylesheet" />
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.1/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous" />
    <!-- Favicon -->
    <link rel="icon" type="image/x-icon" href="\static\assets\icons\favicon.ico" />
    <!-- Bootstrap icons -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" />

    {% block customcss %}
    <style>
      body {
          background-color: #f1c44d; /* Cambia el color de fondo según tus preferencias */
      }
      .bg-light {
          --bs-bg-opacity: 1;
          background-color: #ebcd7a;
      }
    </style>
    {% endblock %}
  </head>
  <body>
    {% comment %}NAVBAR PARA TODOS{% endcomment %}
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container px-4 px-lg-5">
        <a class="navbar-brand" href="{% url 'core:frontendmain' %}">Bibliotinka</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0 ms-lg-4">
            <li class="nav-item">
              <a style="width: 5px;"></a>
            </li>
            <li class="nav-item">
              <form class="form-inline d-flex">
                <input class="form-control mr-sm-2" type="search" placeholder="Search" name="search" aria-label="Search" style="width: 300px;" />
                <div style="width: 5px;"></div>
                <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
              </form>
            </li>
          </ul>
          <form class="d-flex">
            <button id="actualizar_contenido_btn" class="btn btn-outline-dark" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasExample" aria-controls="offcanvasExample">
              <i class="bi-cart-fill me-1"></i>
              <span class="badge bg-dark text-white ms-1 rounded-pill">{{ carrito|length }}</span>
            </button>
          </form>
          {% if user.is_authenticated %}
            <div class="nav-item dropdown px-4">
              <a class="nav-link text-dark dropdown-toggle" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">{{ user }}</a>
              <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                <li>
                  <a class="dropdown-item" href="{% url 'usuario:solicitud_user' %}">Mis solicitudes</a>
                </li>
                <li>
                  <a class="dropdown-item" href="\confUsuario">Configuración</a>
                </li>
                {% if user.is_staff and user.username == 'booker' %}
                <li>
                  <a class="dropdown-item" href="{% url 'bibliotecario:dashboardBooker' %}">Dashboard del Bibliotecario</a>
                </li>
                {% endif %}
                {% if user.is_superuser %}
                  <li>
                    <a class="dropdown-item" href="{% url 'admin:index' %}">Panel de Administrador</a>
                  </li>
                {% endif %}
                <li>
                  <hr class="dropdown-divider" />
                </li>
                <li>
                  <a class="dropdown-item" href="/logingout">Cerrar sesión</a>
                </li>
              </ul>
            </div>
          {% else %}
            <div class="nav-item px-4">
              <a class="nav-link active text-dark" aria-current="page" href="/login">Iniciar sesión</a>
            </div>
          {% endif %}
        </div>
      </div>
    </nav>
    {% comment %}Bandeja{% endcomment %}
    <div class="offcanvas offcanvas-end" tabindex="-1" id="offcanvasExample" aria-labelledby="offcanvasExampleLabel">
      <div class="offcanvas-header">
        <h5 class="offcanvas-title" id="offcanvasExampleLabel">Tus pedidos</h5>
        <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
      </div>
      <div class="offcanvas-body">
        {% comment %}Puede haber una plantilla que recien aparezca cuando se agrege un libro{% endcomment %}
        {% comment %}TODO: Agregar sincronización de bandeja en las pantallas{% endcomment %}
        {% if carrito|length == 0 %}
          <div class="text-center">
            <div class="empty-img">
              <img src="https://component.gallery/static/8d36eaa25b6dcb026685101ebc379022/Empty%20state%20icon..svg" height="128" alt="..." />
            </div>
            <div class="text-center text-dark">
              <h1 class="h1 fw-bolder">¡Oops! Aquí no hay nada.</h1>
              <p class="lead fw-normal text-dark mb-0">Intenta agregar un libro.</p>
            </div>
          </div>
        {% else %}
          <table class="table" id="carrito_table">
            <thead>
              <tr>
                <th scope="col">ISBN</th>
                <th scope="col">Titulo</th>
                <th scope="col">Acción</th>
              </tr>
            </thead>
            <tbody></tbody>
          </table>
          <div class="container mt-4">
            <div class="d-flex justify-content-between">
              <button href="{% url 'core:crear_solicitud' %}" type="button" class="btn btn-primary">Continuar</button>
              <button type="button" class="btn btn-secondary">Limpiar bandeja</button>
            </div>
          </div>
        {% endif %}
      </div>
    </div>
    {% block bodycontent %}{% endblock %}
    <!-- Scripts de Bootstrap y jQuery (asegúrate de incluir jQuery) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js" integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+" crossorigin="anonymous"></script>
    <script src="{% static 'js\plugins\toasts.js' %}"></script>
    {% block customjs %}

    {% endblock %}
  </body>
</html>

biblioteca_online/templates/templates-base/headerFoot.html
{% extends "templates-base/user-base.html" %}

{% block style %}
    <link rel="stylesheet" href="\static\css\bootstrap.min.css">
    <link rel="stylesheet" href="\static\css\templatemo.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Roboto:wght@100;200;300;400;500;700;900&display=swap">
    <link rel="stylesheet" href="\static\css\fontawesome.min.css">

    {% block style2 %}{% endblock style2%}
{% endblock style %}

{% block body %}
<nav class="navbar navbar-expand-lg bg-dark navbar-light d-none d-lg-block" id="templatemo_nav_top">
    <div class="container text-light">
        <div class="w-100 d-flex justify-content-between">
            <div>
                <i class="fa fa-envelope mx-2"></i>
                <a class="navbar-sm-brand text-light text-decoration-none" href="mailto:info@company.com">info@company.com</a>
                <i class="fa fa-phone mx-2"></i>
                <a class="navbar-sm-brand text-light text-decoration-none" href="tel:010-020-0340">010-020-0340</a>
            </div>
            <div>
                <a class="text-light" href="" target="_blank" rel="sponsored"><i class="fab fa-facebook-f fa-sm fa-fw me-2"></i></a>
                <a class="text-light" href="" target="_blank"><i class="fab fa-instagram fa-sm fa-fw me-2"></i></a>
                <a class="text-light" href="" target="_blank"><i class="fab fa-twitter fa-sm fa-fw me-2"></i></a>
                <a class="text-light" href="https://www.linkedin.com/" target="_blank"><i class="fab fa-linkedin fa-sm fa-fw"></i></a>
            </div>
        </div>
    </div>
</nav>
<!-- Close Top Nav -->


<!-- Header -->
<nav class="navbar navbar-expand-lg navbar-light shadow">
    <div class="container d-flex justify-content-between align-items-center">

        <a class="navbar-brand text-success logo h1 align-self-center" href="index.html">
            Bibliotinka
        </a>

        <button class="navbar-toggler border-0" type="button" data-bs-toggle="collapse" data-bs-target="#templatemo_main_nav" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="align-self-center collapse navbar-collapse flex-fill  d-lg-flex justify-content-lg-between" id="templatemo_main_nav">
            <div class="flex-fill">
                <ul class="nav navbar-nav d-flex justify-content-between mx-lg-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="">Libros</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="">Contacto</a>
                    </li>
                </ul>
            </div>
            <!--<div class="navbar align-self-center d-flex">
                <div class="d-lg-none flex-sm-fill mt-3 mb-4 col-7 col-sm-auto pr-3">
                    <div class="input-group">
                        <input type="text" class="form-control" id="inputMobileSearch" placeholder="Search ...">
                        <div class="input-group-text">
                            <i class="fa fa-fw fa-search"></i>
                        </div>
                    </div>
                </div>-->
                <!--<a class="nav-icon d-none d-lg-inline" href="#" data-bs-toggle="modal" data-bs-target="#templatemo_search">
                    <i class="fa fa-fw fa-search text-dark mr-2"></i>
                </a>-->
               <!-- <a class="nav-icon position-relative text-decoration-none" href="#">
                    <i class="fa fa-fw fa-cart-arrow-down text-dark mr-1"></i>
                    <span class="position-absolute top-0 left-100 translate-middle badge rounded-pill bg-light text-dark">7</span>
                </a>-->
                <a class="nav-icon position-relative text-decoration-none" href="#">
                    <i class="fa fa-fw fa-user text-dark mr-3"></i>
                    <!--<span class="position-absolute top-0 left-100 translate-middle badge rounded-pill bg-light text-dark">+99</span>-->
                </a>
            </div>
        </div>

    </div>
</nav>
<!-- Close Header -->

{% block content %}

{% endblock content%}




<!-- Start Footer -->
<footer class="bg-dark" id="tempaltemo_footer">
    <div class="container">
        <div class="row">

            <div class="col-md-4 pt-5">
                <h2 class="h2 text-success border-bottom pb-3 border-light logo">Bibliotinka</h2>
                <ul class="list-unstyled text-light footer-link-list">
                    <li>
                        <i class="fas fa-map-marker-alt fa-fw"></i>
                        123 Consectetur at ligula 10660
                    </li>
                    <li>
                        <i class="fa fa-phone fa-fw"></i>
                        <a class="text-decoration-none" href="tel:010-020-0340">010-020-0340</a>
                    </li>
                    <li>
                        <i class="fa fa-envelope fa-fw"></i>
                        <a class="text-decoration-none" href="mailto:info@company.com">info@company.com</a>
                    </li>
                </ul>
            </div>

            <div class="col-md-4 pt-5">
                <h2 class="h2 text-light border-bottom pb-3 border-light">Categorias</h2>
                <ul class="list-unstyled text-light footer-link-list">
                    <li><a class="text-decoration-none" href="#">Matematica</a></li>
                    <li><a class="text-decoration-none" href="#">Lenguaje</a></li>
                    <li><a class="text-decoration-none" href="#">Cuentos</a></li>
                    <li><a class="text-decoration-none" href="#">Fisica</a></li>
                    <li><a class="text-decoration-none" href="#">Quimica</a></li>
                    <li><a class="text-decoration-none" href="#">Deportes</a></li>
                    <li><a class="text-decoration-none" href="#">Historia</a></li>
                </ul>
            </div>

            <div class="col-md-4 pt-5">
                <h2 class="h2 text-light border-bottom pb-3 border-light">Información</h2>
                <ul class="list-unstyled text-light footer-link-list">
                    <li><a class="text-decoration-none" href="#">Home</a></li>
                    <li><a class="text-decoration-none" href="#">Contacto</a></li>
                    <li><a class="text-decoration-none" href="#">Libros</a></li>
                </ul>
            </div>

        </div>

        <div class="row text-light mb-4">
            <div class="col-12 mb-3">
                <div class="w-100 my-3 border-top border-light"></div>
            </div>
            <div class="col-auto me-auto">
                <ul class="list-inline text-left footer-icons">
                    <li class="list-inline-item border border-light rounded-circle text-center">
                        <a class="text-light text-decoration-none" target="_blank" href="http://facebook.com/"><i class="fab fa-facebook-f fa-lg fa-fw"></i></a>
                    </li>
                    <li class="list-inline-item border border-light rounded-circle text-center">
                        <a class="text-light text-decoration-none" target="_blank" href="https://www.instagram.com/"><i class="fab fa-instagram fa-lg fa-fw"></i></a>
                    </li>
                    <li class="list-inline-item border border-light rounded-circle text-center">
                        <a class="text-light text-decoration-none" target="_blank" href="https://twitter.com/"><i class="fab fa-twitter fa-lg fa-fw"></i></a>
                    </li>
                    <li class="list-inline-item border border-light rounded-circle text-center">
                        <a class="text-light text-decoration-none" target="_blank" href="https://www.linkedin.com/"><i class="fab fa-linkedin fa-lg fa-fw"></i></a>
                    </li>
                </ul>
            </div>
        </div>
    </div>

    <div class="w-100 bg-black py-3">
        <div class="container">
            <div class="row pt-2">
                <div class="col-12">
                    <p class="text-left text-light">
                        Copyright &copy; 2021 Company Name 
                        | Designed by <a rel="sponsored" href="x" target="_blank">AldhairPro</a>
                    </p>
                </div>
            </div>
        </div>
    </div>

    </footer>
    <!-- End Footer -->


    <script src="assets/js/bootstrap.bundle.min.js"></script>

{% endblock body %}
    

biblioteca_online/templates/templates-base/templateGeneral.html
{% extends "templates-base/user-base.html" %}

{% block style %}
    <!-- Enlace al archivo de estilo específico de este template -->
    <link type="text/css" rel="stylesheet" href="\static\css\templateGeneral.css" />
    <!-- Agrega estilos específicos para la tabla si es necesario -->
    <style>
        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
        }

        th, td {
            padding: 12px;
            text-align: left;
            border-bottom: 1px solid #ddd;
        }
    </style>
{% endblock style %}

{% block body %}
<div class="center-container">
    <h1>BIBLIOTINKA Dashboard</h1>
    <div class="info-container">
        <h2>Bienvenido, {{ user.username }}</h2>
    </div>
    <div class="content-container">
        <!-- Contenido específico para el dashboard del administrador/bibliotecario -->
        {% if user.is_staff %}
            <!-- Contenido para el administrador -->
            <p>¡Eres un administrador!</p>
        {% else %}
            <!-- Contenido para el bibliotecario -->
            <p>¡Eres un bibliotecario!</p>
            <!-- Agrega una tabla para mostrar los datos de la base de datos -->
            <table>
                <thead>
                    <tr>
                        <th>Columna 1</th>
                        <th>Columna 2</th>
                        <!-- Agrega más encabezados según tu modelo de datos -->
                    </tr>
                </thead>
                <tbody>
                    {% for item in biblioteca_data %}
                        <tr>
                            <td>{{ item.columna1 }}</td>
                            <td>{{ item.columna2 }}</td>
                            <!-- Agrega más celdas según tu modelo de datos -->
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        {% endif %}
    </div>
</div>
{% endblock body %}

biblioteca_online/templates/templates-base/user-base.html
<!DOCTYPE html>
<html lang="es">
	<head>
		<meta charset="UTF-8" />
		<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
		<meta name="viewport" content="width=device-width, initial-scale=1.0" />
		<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
		{%block style%}{% endblock style %}
		<title>Bibliotinka</title>
	</head>
	<body>
        {% block body %}{% endblock body %}
	</body>
	<script src="https://code.jquery.com/jquery-3.7.1.slim.min.js" integrity="sha256-kmHvs0B+OpCW5GVHUNjv9rOmY0IvSIRcf7zGUDTDQM8=" crossorigin="anonymous"></script>
	<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
	<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js" integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+" crossorigin="anonymous"></script>
	<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
	{%load static%}
	<script src="{% static 'js\plugins\toasts.js' %}"></script>
</html>