biblioteca_online/biblioteca_online/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin', admin.site.urls),
    path('', include('usuario.urls')),
    path('', include('bibliotecario.urls')),
    path('', include('core.urls')),
]

biblioteca_online/bibliotecario/urls.py
# bibliotecario/urls.py

from django.urls import path
from . import views

app_name = "bibliotecario"

urlpatterns = [
    path('panel_bibliotecario', views.panel_bibliotecario, name='panel_bibliotecario'),
    path('libros', views.libros, name='libros'),
    path('prestamos', views.prestamos, name='prestamos'),
    path('dashboardBooker/', views.dashboard_booker, name='dashboardBooker'),
    path('agregar_libro/', views.agregar_libro, name='agregar_libro'),
    path('registrar_ejemplar/', views.registrar_ejemplar, name='registrar_ejemplar'),
    path('registrar_prestamo/', views.registrar_prestamo, name='registrar_prestamo'),
    path('visualizar_prestamos/', views.visualizar_prestamos, name='visualizar_prestamos'),
    path('visualizar_prestamos/modificar/<str:id_prestamo>/', views.modificar_estado_prestamo, name='modificar_estado_prestamo'),
]

biblioteca_online/core/urls.py
from django.urls import path, include
from . import views
app_name = "core"

urlpatterns = [
   path('main/', views.main_frontend, name="frontendmain"),
   path('main/bookdetail/<str:isbn>/', views.bookdetail_frontend, name="bookdetailmain"),
   path('main/prestamo/', include('prestamos.urls')),
   # links que manejan solicitudes del carrito
   path('add_book/', views.add_book, name='add_book'),
   path('crear_solicitud/', views.crear_prestamo, name='crear_solicitud'),
   path('eliminar_libro/', views.eliminar_libro, name='eliminar_libro'),
   path('print_carrito/<int:timestamp>/', views.print_carrito, name='print_carritos'),
]

biblioteca_online/usuario/urls.py
from django.urls import path, include
from . import views

app_name = "usuario"

urlpatterns = [
   path('login/', views.login_user, name="user_login"),
   path('logingout/', views.logout_user, name="user_logout"),
   path('register', views.register, name="user_register"),
   path('', views.home_page, name="welcome_page"),
   path('confUsuario/', views.conf_user, name="configure_page"),
   path('soliUser/', views.solicitud_user, name="solicitud_user"),
   path('confirmar_email/', views.confirmar_email, name='confirmar_email'),
   path('informacion_registro/', views.informacion_registro, name='informacion_registro'),
   path('cambiar_password/', views.cambiar_password, name='cambiar_password'),
   path('eliminar-cuenta/', views.eliminar_cuenta, name='eliminar_cuenta'),
    path('confirmar-eliminar-cuenta/', views.confirmar_eliminar_cuenta, name='confirmar_eliminar_cuenta'),
]

biblioteca_online/bibliotecario/models.py
from django.db import models
from core.models import models

# Create your models here.

biblioteca_online/bibliotecario/forms.py
# En tu archivo forms.py
from django import forms
import requests
from core.models import Libro
from prestamos.models import Ejemplares
from prestamos.models import Prestamo

class LibroForm(forms.ModelForm):
    class Meta:
        model = Libro
        fields = ['categoria', 'title', 'author', 'isbn', 'summary', 'image']
    
    def clean(self):
        cleaned_data = super().clean()
        title = cleaned_data.get('title')
        author = cleaned_data.get('author')

        if not title or not author:
            raise forms.ValidationError('Los campos de título y autor son obligatorios.')
        
    def clean_isbn(self):
        isbn = self.cleaned_data.get('isbn')
        print(f"ISBN a validar: {isbn}")

        # Verifica la existencia de un libro con el mismo ISBN en el catálogo
        if Libro.objects.filter(isbn=isbn).exists():
            print("¡Libro con ISBN existente encontrado!")
            raise forms.ValidationError('Ya existe un libro con este ISBN en el catálogo.')

        # Realiza la validación del ISBN utilizando la API de Open Library
        response = requests.get(f'https://openlibrary.org/isbn/{isbn}.json')
        if response.status_code != 200:
            raise forms.ValidationError('El ISBN ingresado es inválido. Proporcione un ISBN válido.')

        return isbn

class EjemplarForm(forms.ModelForm):
    class Meta:
        model = Ejemplares
        fields = ['libro', 'estado', 'resumen', 'compuesto']
        widgets = {
            'libro': forms.Select(attrs={'required': 'true'}),
            'estado': forms.Select(attrs={'required': 'true'}),
            'resumen': forms.Textarea(attrs={'required': 'true'}),
            'compuesto': forms.TextInput(attrs={'required': 'true'}),
        }

class PrestamoForm(forms.ModelForm):
    class Meta:
        model = Prestamo
        fields = ['id_usuario', 'id_ejemplares', 'prestado_estado', 'fecha_iniprestamo', 'fecha_finprestamo', 'fecha_devolucion']
        widgets = {
            'id_usuario': forms.Select(attrs={'required': 'true'}),
            'id_ejemplares': forms.TextInput(attrs={'required': 'true'}),
            'prestado_estado': forms.Select(attrs={'required': 'true'}),
            'fecha_iniprestamo': forms.DateInput(attrs={'type': 'date'}),
            'fecha_finprestamo': forms.DateInput(attrs={'type': 'date'}),
            'fecha_devolucion': forms.DateInput(attrs={'type': 'date'}),
        }

biblioteca_online/bibliotecario/views.py
import datetime
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render, redirect
from django.contrib import messages
from .forms import LibroForm
from .forms import EjemplarForm
from .forms import PrestamoForm
from core.models import Libro
from usuario.models import Usuario
from core.models import Estado
from prestamos.models import Ejemplares
from prestamos.models import Prestamo
from django.contrib.auth.decorators import login_required

# Create your views here.
def panel_bibliotecario(request):
    # Obtener todas las solicitudes de préstamo
    #solicitudes = SolicitudPrestamo.objects.all()
    
    # Implementa la lógica de búsqueda si es necesario
    #query = request.GET.get('q')
    #if query:
    #    solicitudes = solicitudes.filter(libro__titulo__icontains=query)
    
    return render(request, 'panel_bibliotecario.html')

def libros(request):
    return render (request, 'libros.html')

def prestamos(request):
    return render (request, 'prestamos.html')

# Lo de arriba esta por borrarse, aun no se hace pq puede ocasionar perjuicios al codigo

def dashboard_booker(request):
    libros = Libro.objects.all()  # Obtén todos los registros de libros

    context = {
        'libros': libros,
    }

    return render(request, 'bibliotecario/dashboardBooker.html', context)

def agregar_libro(request):
    if request.method == 'POST':
        form = LibroForm(request.POST)
        if form.is_valid():
            nuevo_libro = form.save()
            return render(request, 'bibliotecario/confirmacion.html', {'libro': nuevo_libro})
    else:
        form = LibroForm()

    return render(request, 'bibliotecario/agregar_libro.html', {'form': form})

def registrar_ejemplar(request):
    if request.method == 'POST':
        form = EjemplarForm(request.POST)
        if form.is_valid():
            # Obtén el libro seleccionado en el formulario
            libro = form.cleaned_data['libro']

            # Guarda el formulario para obtener el ID generado automáticamente
            ejemplar = form.save(commit=False)

            # Establece el estado y el ID del ejemplar según el estado seleccionado
            estado = form.cleaned_data['estado']
            if estado.nombre == 'Reservado':
                ejemplar.id_ejemplar = f"{libro.title}2"
                ejemplar.estado = Estado.objects.get(nombre='Reservado')
            elif estado.nombre == 'Prestado':
                ejemplar.id_ejemplar = f"{libro.title}3"
                ejemplar.estado = Estado.objects.get(nombre='Prestado')
            elif estado.nombre == 'De baja':
                ejemplar.id_ejemplar = f"{libro.title}4"
                ejemplar.estado = Estado.objects.get(nombre='De baja')
            else:  # Default: 'Disponible'
                ejemplar.id_ejemplar = f"{libro.title}1"
                ejemplar.estado = Estado.objects.get(nombre='Disponible')

            # Guarda el ejemplar con el ID actualizado
            ejemplar.save()

            # Puedes realizar otras acciones aquí si es necesario
            return render(request, 'bibliotecario/confirmacionEjemplar.html', {'mensaje': 'Ejemplar registrado con éxito'})
    else:
        form = EjemplarForm()

    return render(request, 'bibliotecario/registrar_ejemplar.html', {'form': form})

def registrar_prestamo(request):
    # Obtener la fecha actual
    fecha_actual = datetime.date.today()

    # Obtener ejemplares disponibles desde la base de datos
    ejemplares_disponibles = Ejemplares.objects.filter(estado__nombre='Disponible')

    # Obtener usuarios desde la base de datos
    usuarios = Usuario.objects.all()

    if request.method == 'POST':
        form = PrestamoForm(request.POST)
        if form.is_valid():
            prestamo = form.save(commit=False)

            # Obtener el nombre de usuario del usuario seleccionado
            usuario_seleccionado = form.cleaned_data['id_usuario']

            # Generar el ID de préstamo automáticamente
            prestamo.id_prestamo = f"{usuario_seleccionado.user.username}{fecha_actual}"

            prestamo.id_ejemplares = form.cleaned_data['id_ejemplares']
            prestamo.save()

            # Actualizar el estado del ejemplar a "prestado"
            ejemplares_ids = [id.strip() for id in prestamo.id_ejemplares.split(',')]
            for ejemplar_id in ejemplares_ids:
                ejemplar = Ejemplares.objects.get(id_ejemplar=ejemplar_id)
                ejemplar.estado = Estado.objects.get(nombre='Reservado')
                ejemplar.save()

            # Imprimir los parámetros del formulario en la consola
            print(f"Prestamo registrado: {prestamo.id_prestamo}, Ejemplares: {prestamo.id_ejemplares}")
            return render(request, 'bibliotecario/confirmacionGeneral.html')  # Ajusta la redirección según tus necesidades
    else:
        form = PrestamoForm()
        
    return render(request, 'bibliotecario/registrar_prestamo.html', {'form': form, 'ejemplares_disponibles': ejemplares_disponibles, 'usuarios': usuarios, 'fecha_actual': fecha_actual})

def visualizar_prestamos(request):
    # Obtener todos los préstamos de la base de datos
    prestamos = Prestamo.objects.all()

    # Lógica para manejar la búsqueda por ID de usuario
    if 'id_usuario' in request.GET:
        id_usuario = request.GET['id_usuario']
        prestamos = prestamos.filter(id_usuario__id=id_usuario)

    return render(request, 'bibliotecario/visualizar_prestamos.html', {'prestamos': prestamos})

def modificar_estado_prestamo(request, id_prestamo):
    # Obtener el préstamo seleccionado
    prestamo = get_object_or_404(Prestamo, id_prestamo=id_prestamo)

    # Lógica para procesar el formulario de modificación
    if request.method == 'POST':
        form = PrestamoForm(request.POST, instance=prestamo)
        if form.is_valid():
            form.save()
            return redirect('bibliotecario/visualizar_prestamos.html')
    else:
        form = PrestamoForm(instance=prestamo)

    return render(request, 'bibliotecario/modificar_estado_prestamo.html', {'form': form})

biblioteca_online/templates/bibliotecario/agregar_libro.html
<!-- En tu archivo templates/agregar_libro.html -->
{% extends "templates-base/user-base.html" %}

{% block body %}
  <h2>Agregar Libro</h2>
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Guardar</button>
  </form>

  {% if form.errors %}
    <div class="error-message">
      <p>Por favor, corrige los siguientes errores:</p>
      {{ form.non_field_errors }}
      {{ form.title.errors }}
      {{ form.author.errors }}
      {{ form.isbn.errors }}
      <!-- Agrega más campos según sea necesario -->
    </div>
  {% endif %}
{% endblock body %} 

biblioteca_online/templates/bibliotecario/confirmacion.html
<!-- En tu archivo templates/confirmacion.html -->
{% extends "templates-base/user-base.html" %}

{% block body %}
  <h2>Libro Agregado</h2>
  <p>Se ha agregado el siguiente libro al catálogo:</p>
  <p>Título: {{ libro.title }}</p>
  <p>Autor: {{ libro.author }}</p>
  <!-- Agrega más detalles según sea necesario -->
{% endblock body %} 

biblioteca_online/templates/bibliotecario/confirmacionEjemplar.html
<!-- En tu archivo templates/confirmacion.html -->
{% extends "templates-base/user-base.html" %}

{% block body %}
  <h2>Ejemplar Agregado</h2>
  <p>Se ha agregado el siguiente ejemplar al catálogo:</p>
  <p>Libro: {{ ejemplar.libro }}</p>
  <p>Estado: {{ ejemplar.estado }}</p>
  <!-- Agrega más detalles según sea necesario -->
{% endblock body %} 

biblioteca_online/templates/bibliotecario/confirmacionGeneral.html
<!-- En tu archivo templates/confirmacion.html -->
{% extends "templates-base/user-base.html" %}

{% block body %}
  <h2>Prestamo Agregado</h2>
  <p>Se ha agregado el siguiente ejemplar al catálogo:</p>
  <!-- Agrega más detalles según sea necesario -->
{% endblock body %} 

biblioteca_online/templates/bibliotecario/dashboardBooker.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
{% block style %}
<head>
  <meta charset="utf-8" />
  <link rel="apple-touch-icon" sizes="76x76" href="{% static 'assets/img/apple-icon.png' %}">
  <link rel="icon" type="image/png" href="{% static 'assets/img/favicon.png' %}">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
  <title>
    Dashboard del Bibliotecario
  </title>
  <meta content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0, shrink-to-fit=no" name="viewport" />
  <!-- Fonts and icons -->
  <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700,200" rel="stylesheet" />
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.1/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
  <!-- CSS Files -->
  <link type="text/css" href="../static/css/bootstrap.min.css" rel="stylesheet" />
  <link type="text/css" href="../static/css/now-ui-dashboard.css" rel="stylesheet" />
</head>
{% endblock style %}
<body class="">
  <div class="wrapper ">
    <div class="sidebar" data-color="orange">
      <div class="logo">
        <a href="#" class="simple-text logo-mini">
          Biblioteca
        </a>
        <a href="#" class="simple-text logo-normal">
          Bibliotecario
        </a>
      </div>
      <div class="sidebar-wrapper" id="sidebar-wrapper">
        <ul class="nav">
          <li class="active">
            <a href="{% url 'core:frontendmain' %}">
              <i class="now-ui-icons design_app"></i>
              <p>Pagina Principal</p>
            </a>
          </li>
          <li>
            <a href="{% url 'bibliotecario:agregar_libro' %}">
              <i class="now-ui-icons education_atom"></i>
              <p>Agregar libro</p>
            </a>
          </li>
          <li>
            <a href="{% url 'bibliotecario:registrar_prestamo' %}">
              <i class="now-ui-icons location_map-big"></i>
              <p>Generar prestamo</p>
            </a>
          </li>
          <li>
            <a href="{% url 'bibliotecario:registrar_ejemplar' %}">
              <i class="now-ui-icons education_atom"></i>
              <p>Agregar ejemplar</p>
            </a>
          </li>
          <li>
            <a href="{% url 'bibliotecario:visualizar_prestamos' %}">
              <i class="now-ui-icons location_map-big"></i>
              <p>Visualizar prestamos</p>
            </a>
          </li>
          <li>
            <a href="{% url 'bibliotecario:dashboardBooker' %}">
              <i class="now-ui-icons ui-1_bell-53"></i>
              <p>Notificaciones</p>
            </a>
          </li>
          <li>
            <a href="{% url 'usuario:configure_page' %}">
              <i class="now-ui-icons users_single-02"></i>
              <p>Perfil de Usuario</p>
            </a>
          </li>
        </ul>
      </div>
    </div>
    <div class="main-panel" id="main-panel">
      <nav class="navbar navbar-expand-lg navbar-transparent bg-primary navbar-absolute">
        <div class="container-fluid">
          <div class="navbar-wrapper">
            <div class="navbar-toggle">
              <button type="button" class="navbar-toggler">
                <span class="navbar-toggler-bar bar1"></span>
                <span class="navbar-toggler-bar bar2"></span>
                <span class="navbar-toggler-bar bar3"></span>
              </button>
            </div>
            <a class="navbar-brand" href="#">Dashboard del Bibliotecario</a>
          </div>
          <!-- Agrega aquí más elementos de la barra de navegación si es necesario -->
        </div>
      </nav>
      <div class="panel-header panel-header-lg">
        <!-- Agrega aquí contenido adicional, como gráficos o estadísticas importantes -->
        <canvas id="statsChart" width="400" height="200"></canvas>
      </div>
      <div class="content">
        <div class="row">
          <!-- Agrega aquí contenido específico del dashboard, como estadísticas, tablas y paneles de control -->
          <div class="col-md-12">
            <div class="card">
              <div class="card-header">
                <h4 class="card-title">Lista de Libros</h4>
              </div>
              <div class="card-body">
                <div class="table-responsive">
                  <table class="table">
                    <thead class="text-primary">
                      <th>Título</th>
                      <th>Autor</th>
                      <th>Género</th>
                      <th>ISBN</th>
                    </thead>
                    <tbody>
                        {% for libro in libros %}
                        <tr>
                            <td>{{ libro.title }}</td>
                            <td>{{ libro.author }}</td>
                            <td>{{ libro.categoria.nombre }}</td>
                            <td>{{ libro.isbn }}</td>
                        </tr>
                        {% endfor %}
                    </tbody>
                  </table>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <footer class="footer">
        <div class="container-fluid">
          <nav>
            <ul>
              <li>
                <a href="https://www.tu-sitio-web.com">
                  Tu Sitio Web
                </a>
              </li>
              <li>
                <a href="#">
                  Acerca de Nosotros
                </a>
              </li>
              <li>
                <a href="#">
                  Blog
                </a>
              </li>
            </ul>
          </nav>
          <div class="copyright" id="copyright">
            &copy; <script>
              document.getElementById('copyright').appendChild(document.createTextNode(new Date().getFullYear()))
            </script>, Diseñado por <a href="https://www.tu-sitio-web.com" target="_blank">Tu Nombre</a>.
          </div>
        </div>
      </footer>
    </div>
  </div>

  <script src="{% static 'js/core/jquery.min.js' %}"></script>
  <script src="{% static 'js/core/popper.min.js' %}"></script>
  <script src="{% static 'js/core/bootstrap.min.js' %}"></script>
  <script src="{% static 'js/plugins/perfect-scrollbar.jquery.min.js' %}"></script>
  <script src="https://maps.googleapis.com/maps/api/js?key=YOUR_KEY_HERE"></script>
  <script src="{% static 'js/plugins/chartjs.min.js' %}"></script>
  <script src="{% static 'js/plugins/bootstrap-notify.js' %}"></script>
  <script src="{% static 'js/now-ui-dashboard.js' %}" type="text/javascript"></script>
  <script>
    // Obtén el lienzo del gráfico
    var ctx = document.getElementById('statsChart').getContext('2d');
  
    // Datos de ejemplo para el gráfico de barras (puedes reemplazarlos con tus propios datos)
    var chartData = {
      labels: ['Enero', 'Febrero', 'Marzo', 'Abril', 'Mayo'],
      datasets: [
        {
          label: 'Prestamos de Libros',
          backgroundColor: 'rgba(75, 192, 192, 0.2)',
          borderColor: 'rgba(75, 192, 192, 1)',
          borderWidth: 1,
          data: [12, 19, 3, 5, 2], // Coloca tus datos aquí
        },
      ],
    };
  
    // Configuración del gráfico
    var chartOptions = {
      responsive: true,
      maintainAspectRatio: false,
    };
  
    // Crea el gráfico de barras
    var myChart = new Chart(ctx, {
      type: 'bar',
      data: chartData,
      options: chartOptions,
    });
  </script>
</body>
</html>

biblioteca_online/templates/bibliotecario/modificar_estado_prestamo.html
<!-- En tu archivo templates/confirmacion.html -->
{% extends "templates-base/user-base.html" %}

{% block body %}
<h1>Modificar Estado de Préstamo</h1>

    <form method="post" action="">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Guardar Cambios">
    </form>
{% endblock body %} 

biblioteca_online/templates/bibliotecario/registrar_ejemplar.html
{% extends "templates-base/user-base.html" %}

{% block body %}
  <h2>Registrar Ejemplar</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Registrar Ejemplar</button>
  </form>

  {% if form.errors %}
    <div class="alert alert-danger">
      <strong>Error:</strong> Por favor, completa todos los campos obligatorios.
    </div>
  {% endif %}
{% endblock body %} 

biblioteca_online/templates/bibliotecario/registrar_prestamo.html
<!-- En tu archivo templates/agregar_libro.html -->
{% extends "templates-base/user-base.html" %}

{% block body %}
<h2>Registrar Préstamo</h2>

    <form method="post" action="">
        {% csrf_token %}
        <!-- Tabla de Ejemplares Disponibles -->
        <div>
            <label for="id_ejemplares">Ejemplares Disponibles:</label>
            <table>
                <thead>
                    <tr>
                        <th>ID Ejemplar</th>
                        <th>Libro</th>
                        <th>Estado</th>
                        <!-- Agrega más encabezados según sea necesario -->
                    </tr>
                </thead>
                <tbody>
                    {% for ejemplar in ejemplares_disponibles %}
                        <tr>
                            <td>{{ ejemplar.id_ejemplar }}</td>
                            <td>{{ ejemplar.libro.title }}</td>
                            <td>{{ ejemplar.estado.nombre }}</td>
                            <!-- Agrega más celdas según sea necesario -->
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>

        {{ form.as_p }}

        <button type="submit">Registrar Ejemplar</button>
    </form>
{% endblock body %} 

biblioteca_online/templates/bibliotecario/visualizar_prestamos.html
<!-- En tu archivo templates/confirmacion.html -->
{% extends "templates-base/user-base.html" %}

{% block body %}
<h1>Lista de Préstamos</h1>

    <!-- Barra de búsqueda por ID de usuario -->
    <form method="get" action="{% url 'bibliotecario:visualizar_prestamos' %}">
        <label for="id_usuario">Buscar por ID de usuario:</label>
        <input type="text" name="id_usuario">
        <input type="submit" value="Buscar">
    </form>

    <!-- Tabla de préstamos -->
    <table border="1">
        <tr>
            <th>ID Préstamo</th>
            <th>ID Usuario</th>
            <th>Fecha Inicio</th>
            <th>Fecha Fin</th>
            <th>Fecha Devolución</th>
            <th>Estado</th>
            <th>Acciones</th>
        </tr>
        {% for prestamo in prestamos %}
        <tr>
            <td>{{ prestamo.id_prestamo }}</td>
            <td>{{ prestamo.id_usuario.id }}</td>
            <td>{{ prestamo.fecha_iniprestamo }}</td>
            <td>{{ prestamo.fecha_finprestamo }}</td>
            <td>{{ prestamo.fecha_devolucion }}</td>
            <td>{{ prestamo.prestado_estado.prestado }}</td>
            <td><a href="{% url 'bibliotecario:modificar_estado_prestamo' prestamo.id_prestamo %}">Modificar Estado</a></td>
        </tr>
        {% endfor %}
    </table>
{% endblock body %} 